# Generated by Django 4.2.10 on 2024-07-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Domains",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("tld", models.CharField(db_index=True, max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "is_new",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewDomains",
            fields=[
                (
                    "domain",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("tld", models.CharField(db_index=True, max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "is_processed",
                    models.BooleanField(blank=True, db_index=True, default=False),
                ),
                ("meh", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZoneList",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "update_interval",
                    models.IntegerField(blank=True, default=1440, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("next_update", models.DateTimeField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Watchman.clients",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Watchman.domains",
                    ),
                ),
            ],
        ),
    ]
