# Generated by Django 4.2.10 on 2024-07-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Watchman", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchMethods",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "is_enabled",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clients",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="clients",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="clients",
            name="max_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Searches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criteria", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_ran", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Watchman.clients",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Watchman.searchmethods",
                    ),
                ),
            ],
        ),
    ]
