# Generated by Django 4.2.10 on 2024-07-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Watchman",
            "0002_searchmethods_clients_is_active_clients_is_verified_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clients",
            new_name="Client",
        ),
        migrations.RenameModel(
            old_name="Domains",
            new_name="Domain",
        ),
        migrations.RenameModel(
            old_name="Matches",
            new_name="Match",
        ),
        migrations.RenameModel(
            old_name="NewDomains",
            new_name="NewDomain",
        ),
        migrations.RenameModel(
            old_name="Searches",
            new_name="Search",
        ),
        migrations.RenameModel(
            old_name="SearchMethods",
            new_name="SearchMethod",
        ),
    ]
