# Generated by Django 4.2.10 on 2024-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Watchman", "0005_search_database_search_tolerance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tdstamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name": "Match", "verbose_name_plural": "Matches"},
        ),
        migrations.AlterModelOptions(
            name="search",
            options={"verbose_name": "Search", "verbose_name_plural": "Searches"},
        ),
        migrations.RemoveField(
            model_name="zonelist",
            name="next_update",
        ),
        migrations.AddField(
            model_name="zonelist",
            name="enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="zonelist",
            name="status",
            field=models.CharField(
                blank=True, db_index=True, default="unknown", max_length=32, null=True
            ),
        ),
    ]
