# Generated by Django 4.2.10 on 2024-08-12 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Watchman", "0007_alter_search_last_completed_alter_search_last_ran_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watch_type",
                    models.CharField(
                        choices=[("mx-exists", "mx-exists"), ("http200", "http200")],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                ("criteria", models.CharField(max_length=255)),
                ("config", models.JSONField(blank=True, null=True)),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2023, 8, 13, 5, 35, 28, 731586, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                (
                    "last_ran",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2023, 8, 13, 5, 35, 28, 731609, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                (
                    "update_interval",
                    models.IntegerField(
                        blank=True, db_index=True, default=1440, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
                (
                    "last_completed",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2023, 8, 13, 5, 35, 28, 731642, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
                (
                    "last_error",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2023, 8, 13, 5, 35, 28, 731660, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="unknown",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Watchman.client",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="search",
            name="last_completed",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 727988, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="last_ran",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 727951, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 727932, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zonelist",
            name="last_completed",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 727252, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zonelist",
            name="last_diffed",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 727271, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zonelist",
            name="last_error",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 727284, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zonelist",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 13, 5, 35, 28, 726677, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hit", models.CharField(db_index=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "is_new",
                    models.BooleanField(blank=True, db_index=True, default=True),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(blank=True, db_index=True, default=False),
                ),
                (
                    "is_fp",
                    models.BooleanField(blank=True, db_index=True, default=False),
                ),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Watchman.watch"
                    ),
                ),
            ],
        ),
    ]
