# Generated by Django 4.2.10 on 2024-07-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Watchman", "0007_rename_tdstamp_actorrecord_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonelist",
            name="last_completed",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
