# Generated by Django 4.2.10 on 2024-07-15 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Watchman", "0009_alter_zonelist_last_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonelist",
            name="last_completed",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 6, 3, 20, 7, 58, 352266),
                null=True,
            ),
        ),
    ]
